### ISSUE TITLE
can't connect via WebSocket: 502 Bad Gateway

### ISSUE THREAD

**Issue by jwilk** [Debian/dcs#84]
I've been using https://github.com/jwilk/dcs-cli as a DCS client, but it recently stopped working:
```console
$ dcs-cli moooooo
Query: moooooo
Traceback (most recent call last):
  File ".../dcs-cli", line 27, in <module>
    lib.cli.main()
  File ".../lib/cli.py", line 104, in main
    send_query(options)
  File ".../lib/cli.py", line 141, in send_query
    header=['User-Agent: ' + user_agent]
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 219, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/lib/python3/dist-packages/websocket/_handshake.py", line 67, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/lib/python3/dist-packages/websocket/_handshake.py", line 123, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d", status)
websocket._exceptions.WebSocketBadStatusException: Handshake status 502
```

There's still WebSocket codepath in `instant.js`, so I guess this should work?

**Comment by stapelberg** [comment]
Thanks for the report. Pushing a fix now.
